platform :ios, '8.0'

target 'CCLocalLibrary' do
  use_frameworks!

 pod 'LocalLib' , :path => '../LocalLib'

#    pod 'MBProgressHUD', '~> 1.0.0'
#    pod 'SDWebImage', '~> 3.8.2'
#    pod 'MJRefresh', '~> 3.1.12'
#    pod 'AFNetworking', '~> 3.1.0'

end
