platform :ios, '11.0'

target 'MQExtension_Example' do
  use_frameworks!

#    pod 'MQExtensionKit/MQFull', :path => '../'

    pod 'MBProgressHUD', '~> 1.2.0'
    pod 'SVProgressHUD', '~> 2.2.5'

    pod 'MGJRouter', '~> 0.10.0'
    pod 'AFNetworking/Reachability', '~> 4.0.1'
    pod 'AFNetworking/UIKit', '~> 4.0.1'
    pod 'SDWebImage', '~> 5.8.0'
    pod 'MJRefresh', '~> 3.4.3'
    
end
