platform :ios, '8.0'

target 'MQExtension_Example' do
  use_frameworks!

#    pod 'MQExtensionKit/MQFull', :path => '../'

    pod 'MBProgressHUD', '~> 1.0.0'

    pod 'Realm', '~> 2.10.0'

    pod 'MGJRouter', '~> 0.9.3'
    pod 'AFNetworking/Reachability', '~> 3.1.0'
    pod 'AFNetworking/UIKit', '~> 3.1.0'
    pod 'SDWebImage', '~> 4.1.0'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'FMDB', '~> 2.7.2'

end
