//
//  YMMethodDef.h
//  ym_sell_ios
//
//  Created by 冯明庆 on 2017/3/29.
//  Copyright © 2017年 冯明庆. All rights reserved.
//

#ifndef YMMethodDef_h
    #define YMMethodDef_h

//#pragma mark - Methods

    #define _YM_MAIN_LOOP_TIMER_ 3.5f
    #define _YM_MAIN_LOOP_MAX_SECTIONS_ 1000
    #define _YM_ALERT_DISMISS_INTERVAL_ 1.f
    #define _YM_MON_DEFAULT_BUTTON_COUNTS_ 4

    #define _YM_DEFAULT_FONT_SIZE_ 11.0f
    #define _YM_DEFAULT_FONT_TITLE_SIZE_ 13.0f
    #define _YM_SYSTEM_FONT_SIZE_ 17.0f

    #define _YM_DEFAULT_SEARCH_ITEM_COUNT_ 20

    #define _YM_GAUSSIAN_BLUR_VALUE_ .1f
    #define _YM_REQUEST_MAXIMUN_COUNT_ 5

    #define _YM_ANIMATION_COMMON_DURATION_ .3f
    #define _YM_ANIMATION_FAST_DURATION_ .05f
    #define _YM_PROGRESS_TIMER_INTERVAL_ .05f

    #define _YM_DECIMAL_POINT_POSITION_ 2

    #define _YM_TIMER_COUNT_DOWN_INTERVAL_ 1.f
    #define _YM_TIMER_COUNT_DOWN_MINUTE_ 60.f

    #define _YM_NETWORK_OVER_TIME_INTERVAL_ 30.f

    //#pragma mark - Appearance

    #define _YM_NAVIGATION_HEIGHT_ 44.0f
    #define _YM_NAVIGATION_Y_ 64.0f
    #define _YM_TABBAR_HEIGHT_ 49.f

    #define _YM_MAIN_COLOR_HEX_ 0xDC1729
    #define _YM_MAIN_COLOR_ ymHexColor(_YM_MAIN_COLOR_HEX_, 1.0f);

    /// JPEG 压缩比
    #define _YM_IMAGE_JPEG_COMPRESSION_QUALITY_ 1.f
    /// 大小限制 KB
    #define _YM_IMAGE_JPEG_COMPRESSION_QUALITY_SIZE_ 400.f
    /// 精度
    #define _YM_IMAGE_JPEG_COMPRESSION_QUALITY_SCALE_ .1f

    /// iPhone 7 Basic 1334.f * 750.f
    #define YM_DYNAMIC_WIDTH(VALUE) (((CGFloat)(VALUE)) / 750.f * [UIScreen mainScreen].bounds.size.width)
    #define YM_DYNAMIC_HEIGHT(VALUE) (((CGFloat)(VALUE)) / 1334.f * [UIScreen mainScreen].bounds.size.height)
    #define YM_DYNAMIC_NAVIGATION_BAR_ITEM_HEIGHT(VALUE) (((CGFloat)(VALUE)) / 90.f * _YM_NAVIGATION_HEIGHT_)

    #define YM_DYNAMIC_WIDTH_SCALE(VALUE) (((CGFloat)(VALUE)) / 750.f)
    #define YM_DYNAMIC_HEIGHT_SCALE(VALUE) (((CGFloat)(VALUE)) / 1334.f)


//#pragma mark - Main

    #define _YM_MAIN_COLLECTION_Y_ (SCREEN_HEIGHT * 0.044977f)

    #define _YM_IS_5_5S_SE_ ([UIScreen instancesRespondToSelector: @selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(640, 1136), [[UIScreen mainScreen] currentMode].size) : NO)
    #define _YM_IS_6_6S_7_  ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(750,1334), [[UIScreen mainScreen] currentMode].size) : NO)

    static inline float _YM_MAIN_DROP_MENU_WIDTH_SCALE_() {
        if (_YM_IS_6_6S_7_) {
            return 0.548666f;
        }
        return _YM_IS_5_5S_SE_ ? 0.628666f : 0.490666f;
    }
    static inline float _YM_MAIN_SEARCH_FIELD_WIDTH_SCALE_() {
        if (_YM_IS_6_6S_7_) {
            return 0.33f;
        }
        return _YM_IS_5_5S_SE_ ? 0.25f : 0.388f;
    }

//#pragma mark - Item Detail
    static inline CGFloat _YM_ITEM_DETAIL_VC_EXTERN_HEIGHT_SCALE_() {
        if (_YM_IS_6_6S_7_) {
            return 0.0187406f;
        }
        return _YM_IS_5_5S_SE_ ? 0.038732f : 0.0145833f;
    }

    #define _YM_ITEM_DETAIL_LABEL_DEFAULT_HEIGHT_ 20.0f

    /*
    #if _YM_IS_5_5S_SE_()
        #define _YM_MAIN_DROP_MENU_WIDTH_SCALE_ 0.490666f 0.628666f
        #define _YM_MAIN_SEARCH_FIELD_WIDTH_SCALE_ 0.388f 0.25f
    #else
        #define _YM_MAIN_DROP_MENU_WIDTH_SCALE_ 0.490666f
        #define _YM_MAIN_SEARCH_FIELD_WIDTH_SCALE_ 0.388f
    #endif
    */

/*
    #define _YM_MAIN_DROP_MENU_CELL_WIDTH_SCALE_ 0.24f
    #define _YM_MAIN_DROP_MENU_NAV_LEFT_SCALE_ 0.04f

    #define _YM_MAIN_NAVIGATION_ITEM_HEIGHT_SCALE_ 0.622222f

    #define _YM_MAIN_LOOP_VIEW_SCALE_ 0.247376f

    #define _YM_MAIN_CELL_WIDTH_SCALE_ 0.461333f
    #define _YM_MAIN_CELL_HEIGHT_SCALE_ 0.383808f

    #define _YM_MAIN_CELL_EDGEINSET_UP_DOWN_SCALE_ 0.022488f
    #define _YM_MAIN_CELL_EDGEINSET_LEFT_RIGHT_SCALE_ 0.029333f
    #define _YM_MAIN_CELL_ITEM_SPACING_SCALE_ 0.021333f
    #define _YM_MAIN_CELL_ITEM_LINE_SPACING_SCALE_ 0.022488f

    #define _YM_MAIN_DROP_MENU_T_B_SCALE_ 0.0140625f

//#pragma mark - Splash Window

    #define _YM_SPLASH_WINDOW_LABEL_SCALE_ 0.206146f
    #define _YM_SPLASH_WINDOW_BUTTON_CONTENT_SCALE_ 0.074962f
    #define _YM_SPLASH_WINDOW_BUTTON_CONTENT_LEFT_RIGHT_SCALE_ 0.241333f
    #define _YM_SPLASH_WINDOW_BUTTON_CONTENT_BASE_HEIGHT_SCALE_ 0.094452f
    #define _YM_SPLASH_WINDOW_BUTTON_HEIGHT_SCALE_ 0.073463f
    #define _YM_SPLASH_WINDOW_BUTTON_SPACING_SCALE_ 0.0187406f

//#pragma mark - Item Detail

    #define _YM_ITEM_DETAIL_COLLECTION_VIEW_SCALE_ 0.448275f

    #define _YM_ITEM_DETAIL_COLLECTION_CELL_HEIGHT_SCALE_ 0.384557f
    #define _YM_ITEM_DETAIL_COLLECTION_CELL_WIDTH_SCALE_ 0.948f
    #define _YM_ITEM_DETAIL_COLLECTION_EDGEINSET_UP_DOWN_SCALE_ 0.031484f
    #define _YM_ITEM_DETAIL_COLLECTION_EDGEINSET_LEFT_RIGHT_SCALE_ 0.029333f

    #define _YM_ITEM_DETAIL_PULL_SCROLL_VIEW_SCALE_ 0.790854f
    #define _YM_ITEM_DETAIL_UI_COMMON_SPACE_SCALE_ 0.016491f

    #define _YM_ITEM_DETAIL_UI_COMMON_SPACING_ (_YM_ITEM_DETAIL_UI_COMMON_SPACE_SCALE_ * SCREEN_HEIGHT)
    #define _YM_ITEM_DETAIL_LABEL_DEFAULT_HEIGHT_ 20.0f
    #define _YM_ITEM_DETAIL_LABEL_SEP_SCALE_ 0.026986f

    #define _YM_ITEM_DETAIL_BUTTONS_CONTENT_SCALE_ 0.150674f
    #define _YM_ITEM_DETAIL_BUTTONS_CELL_HEIGHT_SCALE_ 0.041979f
    #define _YM_ITEM_DETAIL_BUTTONS_CELL_WIDTH_SCALE_ 0.417333f

    #define _YM_ITEM_DETAIL_BUTTONS_BOTTOM_SPACING_SCALE_ 0.022488f

    #define _YM_ITEM_DETAIL_VC_BOTTOM_SCALE_ (_YM_SPLASH_WINDOW_BUTTON_CONTENT_SCALE_)
    #define _YM_ITEM_DETAIL_VC_IMAGEVIEW_SCALE_ 0.071214f

    #define _YM_ITEM_DETAIL_VC_DOWN_HINT_SCALE_ 0.057721f
    #define _YM_ITEM_DETAIL_VC_MON_COUNTRY_SCALE_ 0.029235f

    static inline CGFloat _YM_ITEM_DETAIL_VC_EXTERN_HEIGHT_SCALE_() {
        if (_YM_IS_6_6S_7_) {
            return 0.0187406f;
        }
        return _YM_IS_5_5S_SE_ ? 0.038732f : 0.0145833f;
    }
    //#define _YM_ITEM_DETAIL_VC_EXTERN_HEIGHT_SCALE_ 0.0145833f

//#pragma mark - Add Category
    #define _YM_ADD_CATEGORY_UP_DOWN_SCALE_ 0.043478f
    #define _YM_ADD_CATEGORY_HEIGHT_SCALE_ 0.053973f
    #define _YM_ADD_CATEGORY_LEFT_RIGHT_SPACE_SCALE_ 0.036731f
    #define _YM_ADD_CATEGORY_ITEM_COUNT_RIGHT_SCALE_ 0.036f

//#pragma mark - Shop Manage
    #define _YM_SHOP_MANAGE_HEADER_SCALE_ 0.263868f
    #define _YM_SHOP_MANAGE_SHARE_BUTTON_BOTTOM_SPACE_SCALE_ (_YM_ITEM_DETAIL_UI_COMMON_SPACE_SCALE_)
    #define _YM_SHOP_MANAGE_HEADER_HEIGHT_SCALE_ 0.178666f
    #define _YM_SHOP_MANAGE_HEADER_LEFT_SPACE_ 0.042666f
    #define _YM_SHOP_MANAGE_SHOP_NAME_SCALE_ 0.089955f
    #define _YM_SHOP_MANAGE_SHOP_NAME_LEFT_SPACE_SCALE_ 0.038666f
    #define _YM_SHOP_MANAGE_SHOP_NAME_UP_SPACE_SCALE_ 0.011994f
    #define _YM_SHOP_MANAGE_SECTION_HEADER_HEIGHT_SCALE_ 0.040479f
    #define _YM_SHOP_MANAGE_COMMON_SPACING_ (_YM_ITEM_DETAIL_UI_COMMON_SPACING_)
    #define _YM_SHOP_MANAGE_BUTTON_HEIGHT_SPACING_ 0.053973f 

//#pragma mark - Dynamic
    #define _YM_DYNAMIC_HEAD_IMAGE_UP_SPACING_SCALE_ 0.021739f
    #define _YM_DYNAMIC_COMMON_SPACING_ (_YM_ITEM_DETAIL_UI_COMMON_SPACING_)
    #define _YM_DYNAMIC_HEAD_WIDTH_SCALE_ 0.1f
    #define _YM_DYNAMIC_NAME_LABEL_LEFT_SPACING_SCALE_ 0.017333f
    #define _YM_DYNAMIC_NAME_LABEL_UP_SPACING_SCALE_ 0.029985f
    #define _YM_DYNAMIC_NAME_LABEL_HEIGHT_SPACING_SCALE_ 0.020989f
    #define _YM_DYNAMIC_TIME_LABEL_UP_SPACING_SCALE_ 0.007496f
    #define _YM_DYNAMIC_INFO_LABEL_HEIGHT_SCALE_ (_YM_SPLASH_WINDOW_BUTTON_CONTENT_SCALE_)
    #define _YM_DYNAMIC_CELL_BOTTOM_SPACING_SCALE_ 0.030734f

//#pragma mark - Category Manage
    #define _YM_CATEGORY_MANAGE_SECTION_HEADER_HEIGHT_SCALE_ 0.024737f
    #define _YM_CATEGORY_MANAGE_CELL_HEIGHT_SCALE_ 0.057721f
    #define _YM_CATEGORY_MANAGE_CELL_BOTTOM_HEIGHT_SCALE_ 0.011244f
    #define _YM_CATEGORY_MANAGE_CELL_COMMON_SPACING_ (_YM_SPLASH_WINDOW_BUTTON_CONTENT_SCALE_)
    #define _YM_CATEGORY_MANAGE_CELL_BUTTON_SPACING_SCALE_ 0.041333f

//#pragma mark - Shop Certification Status
    #define _YM_SHOP_CER_PROGRESS_BAR_HEIGHT_ 0.090704f
    #define _YM_SHOP_CER_PROGRESS_VIEW_SPACING_SCALE_ 0.045333f
    #define _YM_SHOP_CER_PROGRESS_VIEW_HEIGHT_SCALE_ 0.011994f
    #define _YM_SHOP_CER_PROGRESS_VIEW_DOT_SCALE_ 0.068f
    #define _YM_SHOP_CER_PROGRESS_VIEW_DOT_SPACING_SCALE_ 0.064f
//    #define _YM_SHOP_CER_PROGRESS_NONE_ 0.1f
//    #define _YM_SHOP_CER_PROGRESS_ERROR_ (1.f - _YM_SHOP_CER_PROGRESS_NONE_)
    #define _YM_SHOP_CER_PROGRESS_LABEL_UP_SPACING_SCALE_ (_YM_SHOP_MANAGE_SHOP_NAME_UP_SPACE_SCALE_)
    #define _YM_SHOP_CER_PROGRESS_LABEL_UP_SCALE_ (_YM_SPLASH_WINDOW_BUTTON_CONTENT_SCALE_)
    #define _YM_SHOP_CER_VC_CENTER_IMAGE_UP_SPACING_SCALE_ 0.272863f
    #define _YM_SHOP_CER_VC_CENTER_IMAGE_SCALE_ 0.074666f
    #define _YM_SHOP_CER_VC_BOTTOM_LABEL_UP_SPACING_SCALE_ 0.044227f

//#pragma mark - Shop Certification Hint View
    #define _YM_SHOP_CER_HINT_CONTENT_VIEW_UP_SCALE_ 0.164917f
    #define _YM_SHOP_CER_HINT_CONTENT_VIEW_LEFT_RIGHT_SCALE_ 0.1f
    #define _YM_SHOP_CER_HINT_CONTENT_VIEW_DOWN_SCALE_ 0.253373f
    #define _YM_SHOP_CER_HINT_CONTENT_HEIGHT_SCALE_ 0.488005f */
//    #define _YM_SHOP_CER_HINT_TITLE_SCALE_ /*0.082458f*/ /*(_YM_SPLASH_WINDOW_BUTTON_CONTENT_SCALE_)*/ 0.078210f
/*
    #define _YM_SHOP_CER_HINT_IMAGE_CONTENT_HEIGHT_SCALE_ 0.254122f
    #define _YM_SHOP_CER_HINT_IMAGE_UP_SCALE_ 0.012743f
    #define _YM_SHOP_CER_HINT_IMAGE_LEFT_RIGHT_SCALE_ 0.066666f
    #define _YM_SHOP_CER_HINT_IMAGE_DOWN_SCALE_ 0.008995f
    #define _YM_SHOP_CER_HINT_IMAGE_HEIGHT_SCALE_ 0.232383f

#pragma mark - Shop Certification Success
    #define _YM_SHOP_CER_SUCCESS_CELL_LABEL_WIDTH_SCALE_ 0.277333f
    #define _YM_SHOP_CER_SUCCESS_CELL_LEFT_RIGHT_SCALE_ 0.049333f
    #define _YM_SHOP_CER_SUCCESS_CELL_HEIGHT_SCALE_ 0.062968f
    #define _YM_SHOP_CER_SUCCESS_CELL_HEIGHT_ (_YM_SHOP_CER_SUCCESS_CELL_HEIGHT_SCALE_ * SCREEN_HEIGHT)
    #define _YM_SHOP_CER_IMAGE_VIEW_HEIGHT_SCALE_ 0.104947f
    #define _YM_SHOP_CER_BUTTON_VIEW_UP_SPACING_SCALE_ 0.044977f
    #define _YM_SHOP_CER_BUTTON_VIEW_LEGT_RIGHT_SPACING_SCALE_ 0.050666f */
//    #define _YM_SHOP_CER_BUTTON_VIEW_PHONE_WIDTH_SCALE_ /*0.649333f*/ 0.734666f
/*
    #define _YM_SHOP_CER_DROPMENU_UP_DOWN_SPACING_SCALE_ 0.008995f
    #define _YM_SHOP_CER_DROPMENU_WIDTH_SCALE_ 0.349333f
    #define _YM_SHOP_CER_DROPMENU_HEIGHT_SCALE_ 0.042728f
*/

#endif
